### ISSUE TITLE
Definir estilização do código e configurar editor

### ISSUE THREAD

**Issue by otthonleao** [otthonleao/clone-tabnews#2]
- [x] Ligar sincronização do editor
- [x] Configurar o Editor Config
- [x] Configurar o Prettier

**Comment by otthonleao** [comment]
# Ligar sincronização do editor
Toda vez que fechar o _codespaces_ e deletar o _workspace_, ele perderá as configurações setadas como a de Tema.
Para não ter esse problema deve-se sincronizar as configurações do Editor na nuvem usando a própria conta do GitHub.

### Como Fazer?
1. Vá em `Profile > Turn on Settings Sync...` e abrirá o editor de configurações mostrando tudo que ele consegue sincronizar.
2. Clique em `Sign in & Turn on` e faça o login com a conta do GitHub ou Microsoft para salvar esses dados.

### Teste
O tema do _codespaces_ é sincronizado com o tema atual do GitHub que está em uso, mas caso queira deixar o GitHub com o tema claro e o Editor com o tema escuro faça o seguinte:
1. Vá em `Settings > Themes > Color Theme`
2. Irá mostrar todos os temas disponíveis e escolha um
**Pronto!** Se você fechar o editor, ir no _codespaces_, deletar ele e criar um novo, esse deve abrir com as configurações setadas anteriormente.

**Comment by otthonleao** [comment]
# Configurar o EditorConfig
O [EditorConfig](https://editorconfig.org) é um Configurador de Editor que define regras de como a IDE deve se comportar, por exemplo na indentação do código.

## Como Funciona?
Por meio de arquivo de texto chamado `.editorconfig` a IDE que interpretar esse arquivo vai adaptar o código as regras definidas antes mesmo de salvar o arquivo.
Você pode escrever um arquivo de configuração para cada diretório do seu projeto. Se um diretório não tiver o arquivo `.editorconfig` ele vai procurar em um nível acima até encontrar o `root = true`.
É importante destacar que algumas IDE's necessitam da extensão para funcionar, como o **EditorConfig for VSCode**

## Como Fazer?
1. Crie um arquivo na raiz do repositório chamado `.editorconfig`
2. Escreva no arquivo criado `root = true`, pois isso vai definir que essa configuração é a principal e será aplicada no mesmo nível de diretório e abaixo também.
3. Podemos identificar o tipo de arquivo que queremos aplicar as regras e temos o `[*]` para todos, `[*.js]`para Javascript, `[*.py]`para Python e muitos outros.
4. A convenção de Javascript determina uma indentação com **dois espaços**, então utilizamos `indent_style = space` e `indent_size = 2`.

Logo, o nosso editor fica assim:
```.editorconfig
root = true

[*]
indent_style = space
indent_size = 2
```

**Comment by filipedeschamps** [comment]
Ficou sensacional @otthonleao !!! Isso que você fez se chama Journaling (ou Diário) e é uma técnica muito poderosa! Eu fiz isso no início do projeto também! Comecei pelo README e depois transportei para o Wiki: https://github.com/filipedeschamps/tabnews.com.br/wiki

**Comment by otthonleao** [comment]
# Configurar o Prettier
O EditorConfig nos auxilia ao escrever o código já no estilo certo, enquanto o **Prettier** é um formatador de código após salvar os arquivos. Ou seja, **ele irá formatar todos os códigos** de acordo com as configurações definidas, até mesmo o que foi desenvolvido sem o auxilio do EditorConfig, **garantindo que todos os arquivos estejam seguindo o mesmo estilo setado**.

## Como Instalar?
1. Utilizando o NPM teremos o mais atualizado `$ npm install prettier --save-dev`
   - `--save-dev` ou `-D`: é um comando para que o Prettier seja salvo como uma dependência somente para desenvolvimento no arquivo `package.json`, no qual será criado uma lista chamada **devDependencies**, assim separando as dependências que o projeto precisa para rodar em produção das de ambiente de desenvolvimento.
2. Ainda no arquivo `package.json` adicione um script de varredura para que o Prettier certifique que está tudo dentro do formato estabelecido.
```JS
{
  "scripts": {
      "lint:check": "prettier --check ."  // Análise que podemos fazer no código antes de rodar ele 
      "lint:fix": "prettier --write ."  // Concerta os warns encontrados na varredura anterior
  }
}
```
3. Para não ter que ficar executando `$ npm run lint:fix` devemos automatizar baixando a extensão Prettier no VSCode.
4. Agora é preciso informar a IDE que deve usar o Prettier ao salvar um arquivo. Vá na engrenagem `manage > settings`
5. Digite no _Search settings_: `Formatter` e irá exibir a opção **Editor: Default Formatter** e nela selecione a opção `Prettier - Code Formatter` para indicar como o formatador padrão.
6. Digite no _Search settings_: `Format on save` para verificar se a opção **Editor: Format On Save** está habilitada.

É importante que o _auto save_ esteja desabilitada para que nos ajude na hora de realizar os testes automatizados em paralelo.
- Digite no _Search settings_: `auto save` e coloque o **Files: Auto Save** em `off` para só salvar ao nosso comando.

**Podemos utilizar o `$ git diff` para visualizar as mudanças realizadas nos arquivos.**
